sudo:
  false
language:
  - scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - .travis/compile-all.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-core.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-leveldb.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-crdt.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-stream.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-spark.sh ++$TRAVIS_SCALA_VERSION
  - .travis/test-vertx.sh ++$TRAVIS_SCALA_VERSION
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
scala:
  - 2.11.7
jdk:
  - oraclejdk8